spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdpokedex?serverTimezone=GMT-3
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        -strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false